---
- hosts: my
  connection: ssh
  gather_facts: true
  become_user: root
  tasks:
    - name: install java in ubuntu 
    - apt: name=openjdk-8-jdk state=present
    - name: set JAVA_HOME
      file: path=/etc/profile.d/java.sh state=present
    - copy: 
        content: |
          export JAVA_HOME=/opt/java-8-openjdk-amd64
        dest: /etc/profile.d/java.sh
    - name: execute source
      shell: source=/etc/profile.d/java.sh
    - name: Download Apache Maven 
      get_url: url=https://archive.apache.org/dist/maven/maven-3/3.5.3/binaries/apache-maven-3.5.3-bin.tar.gz dest=/opt
    - name: untar Maven
      shell: tar -xvf /opt/apache-maven-3.5.3-bin.tar.gz -C /opt
    - name: set MAVEN_HOME
      file: path=/etc/profile.d/maven.sh state=touch
    - copy:
        content: |
          export MAVEN_HOME=/opt/apache-maven-3.5.3
      dest: /etc/profile.d/maven.sh
    - name: execute source
      shell: source=/etc/profile.d/maven.sh
    - name: download Apache tomcat
      get_url: url=https://archive.apache.org/dist/tomcat/tomcat-8/v8.0.1/bin/apache-tomcat-8.0.1.tar.gz dest=/opt
    - name: untar Tomcat
      shell: tar -xvf /opt/apache-tomcat-8.0.1.tar.gz -C /opt
      notify: restart tomcat server
  handlers:
    - name: restart tomcat server
      shell: ./startup.sh
      args:
        chdir: /opt/apache-tomcat-8.0.1/bin
    - name: download jenkins
      get_url: url=https://get.jenkins.io/war-stable/2.319.1/jenkins.war dest=/opt/apache-tomcat-8.5.3/webapps
    
    - name: download git
      command: apt install git -y
      
